/**
 * Database shapes for Finnish sales invoices.
 *
 * Field names match the Supabase columns exactly. Money, quantity, and VAT
 * are PostgreSQL `numeric` values. They are typed as `string` here because a
 * decimal such as 0.10 is not always exact in a JavaScript number. The app
 * converts these strings to integer cents before doing any math.
 */

/** Lifecycle of an invoice. Only `draft` may be edited. */
export type InvoiceStatus = "draft" | "sent" | "paid" | "canceled";

export const invoiceStatusLabel: Record<InvoiceStatus, string> = {
  draft: "Luonnos",
  sent: "Lähetetty",
  paid: "Maksettu",
  canceled: "Peruttu",
};

/**
 * VAT rates the form is allowed to use.
 * 25.5% is the Finnish standard rate. 14% and 10% are the reduced rates.
 * 0% is the zero rate (not the same thing as a sale outside VAT).
 */
export const VAT_RATES = ["25.5", "14", "10", "0"] as const;

/** Suggested units. The field also accepts a short custom value such as "erä". */
export const INVOICE_UNITS = ["kpl", "h", "kg", "m", "pv"] as const;
export type VatRate = (typeof VAT_RATES)[number];

export interface Invoice {
  /** Primary key. Generated by the database. */
  id: string;
  /** Owner. Always the signed-in user (`auth.users.id`). */
  user_id: string;
  /**
   * Official sequential number, for example INV-1001.
   * Stays null while the invoice is a draft, so a number is not used up
   * before the invoice is actually issued.
   */
  invoice_number: string | null;
  /** draft | sent | paid | canceled */
  status: InvoiceStatus;
  /** Laskun päivä. Calendar date `YYYY-MM-DD`. */
  issue_date: string | null;
  /** Eräpäivä. Calculated as issue date + payment terms. */
  due_date: string | null;
  /** Maksuehto in days, for example 14. */
  payment_terms_days: number | null;
  /** Viivästyskorko in percent per year, for example 8.50. */
  interest_rate: string | null;
  /** Toimituspäivä. Optional. */
  delivery_date: string | null;
  /** Ostajan nimi. */
  customer_name: string | null;
  /**
   * Ostajan Y-tunnus, stored in the column name from the schema
   * (`customer_y_tunus`). Format 1234567-8.
   */
  customer_y_tunus: string | null;
  /** Ostajan osoite. */
  customer_address: string | null;
  /** Ostajan sähköposti. */
  customer_email: string | null;
  /**
   * Kotimainen viitenumero (digits only, check digit included).
   * Filled automatically on publish when the user leaves it empty.
   */
  reference_number: string | null;
  /** Veroton loppusumma, decimal string such as "100.00". */
  subtotal_excluding_vat: string;
  /** Verollinen loppusumma, decimal string such as "125.50". */
  total_including_vat: string;
  /**
   * Seller details copied from company_settings when the invoice is published.
   * Empty on drafts, and on invoices published before that copy existed.
   */
  seller_company_name: string | null;
  seller_y_tunus: string | null;
  seller_iban: string | null;
  seller_bic_swift: string | null;
  seller_billing_address: string | null;
  /** When the row was created. */
  created_at: string;
}

/** One company per user. This is the seller block on a Finnish invoice. */
export interface CompanySettings {
  user_id: string;
  company_name: string | null;
  y_tunus: string | null;
  iban: string | null;
  bic_swift: string | null;
  billing_address: string | null;
}

export interface InvoiceItem {
  /** Primary key. Generated by the database. */
  id: string;
  /** Parent invoice. Deleted automatically if the invoice is deleted. */
  invoice_id: string;
  /** What was sold. */
  description: string;
  /** 1-based order of the row on the invoice. */
  position: number;
  /** Määrä. Up to 3 decimal places, decimal string such as "1.500". */
  quantity: string;
  /** Yksikkö, for example kpl or h. */
  unit: string;
  /** Á-hinta without VAT. Decimal string such as "10.00". */
  unit_price: string;
  /** One of 25.5, 14, 10, or 0. */
  vat_percentage: string;
  /** quantity × unit price, rounded to cents. Decimal string. */
  line_subtotal: string;
  /** Line subtotal + VAT for this row, rounded to cents. Decimal string. */
  line_total: string;
}

/** Invoice plus its rows, as returned by the editor. */
export interface InvoiceWithItems extends Invoice {
  invoice_items: InvoiceItem[];
}
